#ifndef @_P@_VERSION_H_
#define @_P@_VERSION_H_

#define @_P@_VERSION "@PROJECT_VERSION@"
#define @_P@_MAJOR_VERSION @PROJECT_VERSION_MAJOR@
#define @_P@_MINOR_VERSION @PROJECT_VERSION_MINOR@
#define @_P@_PATCH_VERSION @PROJECT_VERSION_PATCH@

#endif  // @_P@_VERSION_H_