name: Build

on:
  push:

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache CPM Dependencies
        uses: actions/cache@v4
        with:
          path: dependencies
          key: ${{ runner.os }}-cpm-${{ hashFiles('cmake/dependencies.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.22.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libgl1-mesa-dev xorg-dev

      - name: Verify
        run: |
          cmake --version
          ninja --version

      - name: Build
        run: |
          make build